# Generated by Django 2.2.6 on 2019-11-04 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20191104_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users_following',
            field=models.ManyToManyField(blank=True, related_name='profile_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
