# Generated by Django 2.2.4 on 2019-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderatin',
            field=models.BooleanField(default=False),
        ),
    ]
