# Generated by Django 2.2.4 on 2019-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitt', '0002_post_moderatin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
