# Generated by Django 2.2.6 on 2019-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitt', '0007_auto_20191025_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=123, max_length=250, unique_for_date='created_date'),
            preserve_default=False,
        ),
    ]
