# Generated by Django 2.2.6 on 2019-10-29 18:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('skitt', '0008_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='moderatin',
            new_name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
