# Generated by Django 2.2.6 on 2019-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skitt', '0011_auto_20191030_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
